version: "3.9"

services:
    database:
        image: mysql:8.0
        container_name: iberian_motosport_mysql
        networks:
            - iberian-motosport-network
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: IberianMotorSportDev
            MYSQL_PASSWORD: password
#        volumes:
#            - "C:/Users/Roger/Desktop/Work/Iberian Motorsport/Docker/Volumes:/var/lib/mysql/data"
        ports:
            - 3306:3306

    service:
        build:
            dockerfile: Dockerfile
        container_name: iberian_motosport_service
        networks:
            - iberian-motosport-network
        ports:
            - 8080:8080
        depends_on:
            - database

networks:
    iberian-motosport-network:
        driver: bridge